FROM vectorim/element-web:v1.11.0

COPY ./element-config/logos /app/themes/element/img/logos
COPY ./element-config/fonts/Dana-Regular.woff /app/fonts
COPY ./element-config/fonts/style.css /app/fonts
COPY ./element-config/config.json /app
COPY ./element-config/fa.866e2e5.json /app/i18n
COPY ./element-config/languages.8cc7d18.json /app/i18n
COPY ./element-config/index.html /app
COPY ./element-config/mobile_guide /app/mobile_guide
